pub struct Theme {
    pub background: &'static str,
    pub surface: &'static str,
    pub primary: &'static str,
    pub on_primary: &'static str,
    pub on_surface: &'static str,
    pub on_background: &'static str,
    pub error_color: &'static str,
    pub border: &'static str,
    pub input_background: &'static str,
    pub user_message_bg: &'static str,
    pub sena_message_bg: &'static str,
    pub debug_background: &'static str,
    pub debug_text: &'static str,
    pub font_size_body: f32,
    pub font_size_small: f32,
    pub font_size_header: f32,
    pub spacing_sm: f32,
    pub spacing_md: f32,
    pub spacing_lg: f32,
    pub input_height: f32,
    pub border_radius: f32,
}

pub const SENA_THEME: Theme = Theme {
    background: "rgb(26, 26, 46)",
    surface: "rgb(22, 33, 62)",
    primary: "rgb(15, 52, 96)",
    on_primary: "rgb(232, 232, 232)",
    on_surface: "rgb(200, 200, 212)",
    on_background: "rgb(224, 224, 232)",
    error_color: "rgb(231, 76, 60)",
    border: "rgb(42, 42, 74)",
    input_background: "rgb(13, 27, 42)",
    user_message_bg: "rgb(26, 54, 93)",
    sena_message_bg: "rgb(45, 27, 78)",
    debug_background: "rgb(10, 10, 26)",
    debug_text: "rgb(102, 255, 102)",
    font_size_body: 15.0,
    font_size_small: 12.0,
    font_size_header: 18.0,
    spacing_sm: 4.0,
    spacing_md: 8.0,
    spacing_lg: 16.0,
    input_height: 44.0,
    border_radius: 8.0,
};