//! Priority-ordered async thought queue.
//!
//! Thoughts are ordered by relevance score (highest first). Expired thoughts
//! are silently discarded at pop time. Max depth enforced at push time.

use crate::config::ExpiryWindows;
use crate::error::CtpError;
use ordered_float::OrderedFloat;
use std::cmp::Ordering;
use std::collections::BinaryHeap;
use std::time::Instant;
use tokio::sync::{Mutex, Notify};
use uuid::Uuid;

/// A candidate thought generated by the generation pipeline.
#[derive(Debug, Clone)]
pub struct Thought {
    pub id: Uuid,
    pub content: String,
    pub score: f32,
    pub expires_at: Instant,
    pub generated_at: Instant,
}

/// Wrapper for BinaryHeap ordering — highest score pops first.
struct ScoredThought(Thought);

impl PartialEq for ScoredThought {
    fn eq(&self, other: &Self) -> bool {
        OrderedFloat(self.0.score) == OrderedFloat(other.0.score)
    }
}

impl Eq for ScoredThought {}

impl PartialOrd for ScoredThought {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for ScoredThought {
    fn cmp(&self, other: &Self) -> Ordering {
        // Highest score first (max-heap)
        OrderedFloat(self.0.score).cmp(&OrderedFloat(other.0.score))
    }
}

/// Async priority-ordered thought queue.
pub struct ThoughtQueue {
    heap: Mutex<BinaryHeap<ScoredThought>>,
    notify: Notify,
}

impl ThoughtQueue {
    pub fn new() -> Self {
        Self {
            heap: Mutex::new(BinaryHeap::new()),
            notify: Notify::new(),
        }
    }

    /// Push a thought into the queue. Returns `CtpError::QueueFull` if at max depth.
    pub async fn push(&self, thought: Thought, max_depth: usize) -> Result<(), CtpError> {
        let mut heap = self.heap.lock().await;
        if heap.len() >= max_depth {
            return Err(CtpError::QueueFull);
        }
        heap.push(ScoredThought(thought));
        drop(heap);
        self.notify.notify_one();
        Ok(())
    }

    /// Pop the highest-scoring non-expired thought. Awaits a push notification
    /// if the queue is empty. Expired thoughts are discarded silently.
    pub async fn pop(&self) -> Option<Thought> {
        loop {
            {
                let mut heap = self.heap.lock().await;
                while let Some(scored) = heap.pop() {
                    if scored.0.expires_at > Instant::now() {
                        return Some(scored.0);
                    }
                    // Expired — discard silently, try next
                    tracing::trace!(
                        event_type = "thought_expired",
                        thought_id = %scored.0.id,
                        relevance_score = scored.0.score,
                        "expired thought discarded from queue"
                    );
                }
            }
            // Queue is empty — wait for a push notification
            self.notify.notified().await;
        }
    }

    /// Return the current number of items in the queue (including possibly expired ones).
    #[cfg(test)]
    pub async fn len(&self) -> usize {
        self.heap.lock().await.len()
    }
}

/// Compute the expiry instant for a thought based on its score and config.
/// High scores get longer expiry windows; low scores expire faster.
/// Score cutoffs come from config — never hardcoded.
pub fn expiry_for_score(score: f32, config: &ExpiryWindows) -> Instant {
    let duration_secs = if score >= config.high_score_cutoff {
        config.high_relevance_secs
    } else if score >= config.medium_score_cutoff {
        config.medium_relevance_secs
    } else {
        config.low_relevance_secs
    };
    Instant::now() + std::time::Duration::from_secs(duration_secs)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_thought(content: &str, score: f32, expires_secs: u64) -> Thought {
        Thought {
            id: Uuid::new_v4(),
            content: content.to_string(),
            score,
            expires_at: Instant::now() + std::time::Duration::from_secs(expires_secs),
            generated_at: Instant::now(),
        }
    }

    #[tokio::test]
    async fn test_push_and_pop_returns_thought() {
        let queue = ThoughtQueue::new();
        let thought = make_thought("test thought", 0.5, 60);
        let content = thought.content.clone();

        queue.push(thought, 10).await.expect("test: push should succeed");
        let popped = queue.pop().await;
        assert!(popped.is_some());
        assert_eq!(popped.unwrap().content, content);
    }

    #[tokio::test]
    async fn test_priority_ordering_high_before_low() {
        let queue = ThoughtQueue::new();

        let low = make_thought("low", 0.3, 60);
        let high = make_thought("high", 0.9, 60);

        queue.push(low, 10).await.expect("test: push low");
        queue.push(high, 10).await.expect("test: push high");

        let first = queue.pop().await.expect("test: first pop");
        assert_eq!(first.content, "high");
        assert_eq!(first.score, 0.9);

        let second = tokio::time::timeout(
            std::time::Duration::from_millis(100),
            queue.pop(),
        )
        .await;
        assert!(second.is_ok());
        assert_eq!(second.unwrap().unwrap().content, "low");
    }

    #[tokio::test]
    async fn test_expired_thought_discarded_silently() {
        let queue = ThoughtQueue::new();

        // Create a thought that is already expired
        let expired = Thought {
            id: Uuid::new_v4(),
            content: "expired".to_string(),
            score: 0.9,
            expires_at: Instant::now() - std::time::Duration::from_secs(1),
            generated_at: Instant::now(),
        };

        queue.push(expired, 10).await.expect("test: push expired");

        // Pop should not return the expired thought — it should wait for more
        let result = tokio::time::timeout(
            std::time::Duration::from_millis(100),
            queue.pop(),
        )
        .await;

        // Should time out because the expired thought was discarded
        assert!(result.is_err(), "pop should time out — no valid thoughts");
    }

    #[tokio::test]
    async fn test_queue_full_returns_error() {
        let queue = ThoughtQueue::new();

        // Fill to max_depth of 2
        queue
            .push(make_thought("a", 0.5, 60), 2)
            .await
            .expect("test: push 1");
        queue
            .push(make_thought("b", 0.5, 60), 2)
            .await
            .expect("test: push 2");

        // Third push should fail
        let result = queue.push(make_thought("c", 0.5, 60), 2).await;
        assert!(
            matches!(result, Err(CtpError::QueueFull)),
            "expected QueueFull error"
        );
    }

    #[test]
    fn test_expiry_window_from_score() {
        let config = ExpiryWindows {
            high_relevance_secs: 300,
            medium_relevance_secs: 120,
            low_relevance_secs: 30,
            high_score_cutoff: 0.8,
            medium_score_cutoff: 0.4,
        };

        let now = Instant::now();

        let high_expiry = expiry_for_score(0.9, &config);
        assert!(high_expiry > now + std::time::Duration::from_secs(299));

        let medium_expiry = expiry_for_score(0.5, &config);
        assert!(medium_expiry > now + std::time::Duration::from_secs(119));
        assert!(medium_expiry < now + std::time::Duration::from_secs(125));

        let low_expiry = expiry_for_score(0.2, &config);
        assert!(low_expiry > now + std::time::Duration::from_secs(29));
        assert!(low_expiry < now + std::time::Duration::from_secs(35));
    }

    #[tokio::test]
    async fn test_pop_wakes_on_push() {
        use std::sync::Arc;

        let queue = Arc::new(ThoughtQueue::new());
        let queue_clone = Arc::clone(&queue);

        // Spawn a pop task that will block waiting
        let pop_handle: tokio::task::JoinHandle<Option<Thought>> = tokio::spawn(async move {
            queue_clone.pop().await
        });

        // Give the pop task time to start waiting
        tokio::time::sleep(std::time::Duration::from_millis(10)).await;
        assert!(!pop_handle.is_finished());

        // Push a thought — should wake the pop task
        queue
            .push(make_thought("wake up", 0.5, 60), 10)
            .await
            .expect("test: push");

        let result = tokio::time::timeout(
            std::time::Duration::from_millis(100),
            pop_handle,
        )
        .await;

        assert!(result.is_ok(), "pop should have woken up");
        let thought = result.unwrap().unwrap().unwrap();
        assert_eq!(thought.content, "wake up");
    }
}
